### ISSUE TITLE
Implement parameters relevant to new consensus rules after fork activation

### ISSUE THREAD

**Issue by ftrader** [ftrader-bitcoinunlimited/BitcoinUnlimited#3]
There are some parameters relevant to new consensus after the fork. These are the most critical parameters to provide. Initially they can be hardcoded with dummy values.

The two I can think of right now:
- the activation time (POSIX timestamp)
- the default minimum EB to be required to follow the fork smoothly [1]

This task is to make them available in a suitable way so that they can be read / written by other parts of the software.

NOTE: Consider that we probably need to configure them per-chain (mainnet, testnet, nolnet, regtestnet) in order to conduct testing.

[1] 8MB so far, ref. https://github.com/BitcoinUnlimited/BUIP/pull/32

**Comment by gandrewstone** [comment]
implemented by https://github.com/ftrader-bitcoinunlimited/BitcoinUnlimited/pull/6

**Comment by ftrader** [comment]
Closed as implemented by BUcash release.
